name: ${baseName}
main: ${basePackage}.${baseName}
version: ${version}
description: ${description}
api-version: ${apiVersion}
author: UberPilot
libraries:
  - "org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}"
  - "org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:${coroutinesVersion}"
  - "com.fasterxml.jackson.module:jackson-module-kotlin:${jacksonVersion}"
  - "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${jacksonVersion}"
